---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: trident-csi
subjects:
  - kind: ServiceAccount
    name: trident-csi
    namespace: trident
roleRef:
  kind: ClusterRole
  name: trident-csi
  apiGroup: rbac.authorization.k8s.io
