---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: trident-node-linux
  labels:
    app: node.csi.trident.netapp.io
subjects:
  - kind: ServiceAccount
    name: trident-node-linux
    namespace: trident
roleRef:
  kind: ClusterRole
  name: trident-node-linux
  apiGroup: rbac.authorization.k8s.io
