
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: trident-controller
  labels:
    app: controller.csi.trident.netapp.io
    kubectl.kubernetes.io/default-container: trident-main
spec:
  privileged: false
  allowPrivilegeEscalation: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - hostPath
  - projected
  - emptyDir
