---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: trident-node-linux
  namespace: trident
  labels:
    kubectl.kubernetes.io/default-container: trident-main
    app: node.csi.trident.netapp.io
subjects:
  - kind: ServiceAccount
    name: trident-node-linux
    apiGroup: ""
roleRef:
  kind: Role
  name: trident-node-linux
  apiGroup: rbac.authorization.k8s.io
