
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: trident-node-linux
  labels:
    app: node.csi.trident.netapp.io
    kubectl.kubernetes.io/default-container: trident-main
spec:
  privileged: true
  allowPrivilegeEscalation: true
  hostIPC: true
  hostPID: true
  hostNetwork: true
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - hostPath
  - projected
  - emptyDir
